# Generated by Django 2.2.1 on 2019-06-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0002_bookingform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingform',
            new_name='book',
        ),
    ]
