# Generated by Django 2.2.1 on 2019-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0003_auto_20190628_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Phone',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='adults',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='children',
            field=models.IntegerField(max_length=100),
        ),
    ]
