# Generated by Django 2.2.1 on 2019-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0005_auto_20190628_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='children',
            field=models.IntegerField(),
        ),
    ]
