# Generated by Django 2.2.1 on 2019-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0006_auto_20190628_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Email',
            field=models.CharField(max_length=300),
        ),
    ]
