# Generated by Django 2.2.1 on 2019-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0007_auto_20190628_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='adults',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='children',
            field=models.BigIntegerField(),
        ),
    ]
