# Generated by Django 2.2.1 on 2019-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0008_auto_20190628_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
