# Generated by Django 2.2.1 on 2019-07-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0009_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='Username',
        ),
    ]
