# Generated by Django 2.2.1 on 2019-07-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0010_auto_20190701_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='Password',
        ),
    ]
