# Generated by Django 2.2.1 on 2019-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookitup', '0011_auto_20190701_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=300)),
                ('upassword', models.CharField(max_length=100)),
                ('ure_password', models.CharField(max_length=100)),
            ],
        ),
    ]
